In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
train = pd.read_csv(".\\data\\train.csv")

In [6]:
X = train[['laptop_ID','Inches']]

In [7]:
y = train[['Price_euros']]

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [10]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [11]:
model.fit(X,y)

LinearRegression()

In [12]:
pred = model.predict(X_test)
pred

array([[1130.98843482],
       [1063.69275523],
       [1064.24165963],
       [1183.66802344],
       [1247.23115311],
       [1002.61293788],
       [1176.87684276],
       [1075.40646616],
       [1069.29158012],
       [1084.27467889],
       [1151.10558908],
       [1140.96326103],
       [1108.29104579],
       [1044.43784595],
       [1146.82413475],
       [1153.47828138],
       [1085.23706094],
       [1046.1342436 ],
       [1200.5895129 ],
       [1125.59393779],
       [1170.50955171],
       [1184.4517235 ],
       [1081.69681959],
       [1091.90644145],
       [1135.47421702],
       [1175.87358095],
       [1106.9993211 ],
       [1137.99917726],
       [1066.87640076],
       [1129.10692596],
       [1051.77953834],
       [1012.80732585],
       [1205.31009075],
       [1162.04119004],
       [1127.50269983],
       [1079.83054462],
       [1194.990688  ],
       [1116.33069592],
       [1114.54855596],
       [1201.24819818],
       [1196.30805857],
       [1112.874

In [13]:
from sklearn.metrics import mean_squared_error
import numpy as np

print('RMSE :',np.sqrt(mean_squared_error(y_test,pred)))

RMSE : 703.6904667413233


In [14]:
X_pred = pd.read_csv("data/test.csv")
X_pred.head()

laptop_ID   Company          Product            TypeName  Inches  \
0        750   Toshiba  Tecra X40-D-10G            Notebook    14.0   
1        726  Mediacom    Smartbook 142            Notebook    14.0   
2        633  Mediacom    SmartBook 140            Notebook    14.0   
3        363      Dell    Inspiron 7577              Gaming    15.6   
4        319      Asus    VivoBook Flip  2 in 1 Convertible    11.6   

                            ScreenResolution  \
0  IPS Panel Full HD / Touchscreen 1920x1080   
1                IPS Panel Full HD 1920x1200   
2                          Full HD 1920x1080   
3                          Full HD 1920x1080   
4                       Touchscreen 1366x768   

                                    Cpu  Ram              Memory  \
0            Intel Core i5 7200U 2.5GHz  8GB           256GB SSD   
1              Intel Atom Z8350 1.92GHz  4GB            32GB HDD   
2           Intel Atom x5-Z8350 1.44GHz  2GB  32GB Flash Storage   
3           Intel Core i5 7300HQ 2.5GHz  8GB             1TB HDD   
4  Intel Celeron Dual Core N3350 1.1GHz  2GB  32GB Flash Storage   

                       Gpu       OpSys  Weight  
0    Intel HD Graphics 620  Windows 10  1.25kg  
1    Intel HD Graphics 400  Windows 10   1.4kg  
2        Intel HD Graphics  Windows 10   1.4kg  
3  Nvidia GeForce GTX 1050  Windows 10  2.65kg  
4    Intel HD Graphics 500  Windows 10   1.1kg

In [15]:
X_pred=X_pred[['laptop_ID','Inches']]

In [16]:
predictions_submit = model.predict(X_pred)
predictions_submit

array([[1097.6423004 ],
       [1095.00755928],
       [1084.79793741],
       [1101.01825451],
       [ 981.53500887],
       [1062.70472731],
       [1123.17875843],
       [1136.91660235],
       [1100.68891187],
       [1171.05845611],
       [1061.49713762],
       [1039.67799563],
       [1120.5592512 ],
       [1084.55112248],
       [1067.42530516],
       [1144.60126397],
       [1008.086748  ],
       [1087.21311678],
       [1117.59516743],
       [1166.6672209 ],
       [1136.28517025],
       [1137.01114934],
       [1201.1384173 ],
       [1195.5395924 ],
       [1155.57935199],
       [1095.22712104],
       [1205.96877603],
       [1141.07304191],
       [1087.734768  ],
       [1145.58929189],
       [1069.84048452],
       [1117.48538655],
       [1169.08240026],
       [1183.02457206],
       [1166.99656354],
       [1048.59589281],
       [1143.28389341],
       [1069.57766753],
       [1078.759989  ],
       [1072.74768646],
       [1196.62216731],
       [1063.582

In [22]:
predictions_submit = model.predict(X_pred)
predictions_submit

array([[1097.6423004 ],
       [1095.00755928],
       [1084.79793741],
       [1101.01825451],
       [ 981.53500887],
       [1062.70472731],
       [1123.17875843],
       [1136.91660235],
       [1100.68891187],
       [1171.05845611],
       [1061.49713762],
       [1039.67799563],
       [1120.5592512 ],
       [1084.55112248],
       [1067.42530516],
       [1144.60126397],
       [1008.086748  ],
       [1087.21311678],
       [1117.59516743],
       [1166.6672209 ],
       [1136.28517025],
       [1137.01114934],
       [1201.1384173 ],
       [1195.5395924 ],
       [1155.57935199],
       [1095.22712104],
       [1205.96877603],
       [1141.07304191],
       [1087.734768  ],
       [1145.58929189],
       [1069.84048452],
       [1117.48538655],
       [1169.08240026],
       [1183.02457206],
       [1166.99656354],
       [1048.59589281],
       [1143.28389341],
       [1069.57766753],
       [1078.759989  ],
       [1072.74768646],
       [1196.62216731],
       [1063.582

In [51]:
sbs = [float(x) for x in predictions_submit]

C:\Users\camil\AppData\Local\Temp\ipykernel_23144\3220756750.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  sbs = [float(x) for x in predictions_submit]


In [52]:
sbs

[1097.642300403762,
 1095.0075592778558,
 1084.7979374149686,
 1101.0182545123441,
 981.5350088719618,
 1062.7047273064563,
 1123.1787584293493,
 1136.9166023528178,
 1100.6889118716058,
 1171.058456109354,
 1061.4971376237493,
 1039.6779956338228,
 1120.5592511961495,
 1084.5511224754296,
 1067.4253051570386,
 1144.6012639700446,
 1008.0867479988108,
 1087.2131167803827,
 1117.5951674295047,
 1166.66722089951,
 1136.285170250388,
 1137.0111493403574,
 1201.1384172967846,
 1195.5395924042336,
 1155.5793519946542,
 1095.2271210383478,
 1205.9687760276129,
 1141.073041909463,
 1087.7347680025664,
 1145.5892918922596,
 1069.8404845224527,
 1117.4853865492587,
 1169.0824002649242,
 1183.0245720561784,
 1166.9965635402482,
 1048.5958928096206,
 1143.2838934070915,
 1069.5776675261484,
 1078.7599890014335,
 1072.747686463762,
 1196.622167313988,
 1063.582974348425,
 1030.5918284492607,
 995.7912894112479,
 1065.5590301928548,
 1129.7808451368214,
 1071.2676359656518,
 1167.6400149290184,
 12

In [18]:
sample = pd.read_csv("data/sample_submission.csv")

In [20]:
sample.head()

laptop_ID  Price_euros
0        750          500
1        726          500
2        633          500
3        363          650
4        319          650

In [25]:
sample['laptop_ID']

0       750
1       726
2       633
3       363
4       319
       ... 
386     693
387    1132
388      49
389    1243
390     924
Name: laptop_ID, Length: 391, dtype: int64

In [53]:
submission = pd.DataFrame({"laptop_ID": sample['laptop_ID'], "Price_euros":sbs})

In [54]:
submission.head()

laptop_ID  Price_euros
0        750  1097.642300
1        726  1095.007559
2        633  1084.797937
3        363  1101.018255
4        319   981.535009

In [55]:
def chequeator(df_to_submit):
    """
    Esta función se asegura de que tu submission tenga la forma requerida por Kaggle.
    
    Si es así, se guardará el dataframe en un `csv` y estará listo para subir a Kaggle.
    
    Si no, LEE EL MENSAJE Y HAZLE CASO.
    
    Si aún no:
    - apaga tu ordenador, 
    - date una vuelta, 
    - enciendelo otra vez, 
    - abre este notebook y 
    - leelo todo de nuevo. 
    Todos nos merecemos una segunda oportunidad. También tú.
    """
    if df_to_submit.shape == sample.shape:
        if df_to_submit.columns.all() == sample.columns.all():
            if df_to_submit.laptop_ID.all() == sample.laptop_ID.all():
                print("You're ready to submit!")
                submission.to_csv("submission.csv", index = False) #muy importante el index = False
                urllib.request.urlretrieve("https://i.kym-cdn.com/photos/images/facebook/000/747/556/27a.jpg", "gfg.png")     
                img = Image.open("gfg.png")
                img.show()   
            else:
                print("Check the ids and try again")
        else:
            print("Check the names of the columns and try again")
    else:
        print("Check the number of rows and/or columns and try again")
        print("\nMensaje secreto de Clara: No me puedo creer que después de todo este notebook hayas hecho algún cambio en las filas de `diamonds_test.csv`. Lloro.")


In [57]:
chequeator(submission)

You're ready to submit!


NameError: name 'urllib' is not defined