![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [1]:
import numpy as np
np.__version__

'1.26.0'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [2]:
my_array = np.arange(0,10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [3]:
print(np.array([True, True, True, True, True, True, True, True, True]).reshape(3,3))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [4]:
a = my_array % 2 != 0
print(my_array[a])

[1 3 5 7 9]


[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [5]:
my_array2 = my_array.copy()
b = my_array2 % 2 != 0
my_array2[b] = -1
print(my_array2)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [6]:
print(np.where(my_array % 2 != 0, -1, my_array))

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [7]:
my_array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [8]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(np.concatenate([a,b]))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [9]:
print(np.concatenate([a,b], axis=1))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [10]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.intersect1d(a,b))

[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [12]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [23]:
my_array = np.arange(10)
my_array*10
my_array[1]
my_array[-1]
print(my_array[1:8])

[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [24]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [26]:
np.arange(1,50,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [29]:
np.arange(4,1,-0.25)

array([4.  , 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2.  , 1.75, 1.5 ,
       1.25])

## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

In [33]:
from skimage.io import imread
imagen = imread("./img/numpy.png")
print(type(imagen))
print(imagen.shape)


<class 'numpy.ndarray'>
(306, 765, 4)


## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [39]:
ej_17 = np.arange(1,5).reshape(4,1)
print(ej_17)

print(ej_17.reshape(2,2))


[[1]
 [2]
 [3]
 [4]]
[[1 2]
 [3 4]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [48]:
ej_18 = np.random.randint(0,100,size=(4,5,3))
print(ej_18)

[[[23 38 37]
  [34 56 86]
  [ 0 85 16]
  [68 20 98]
  [42 83 76]]

 [[45 81 54]
  [86 21 25]
  [48 16  7]
  [93 11 33]
  [ 8 89 46]]

 [[99 81 22]
  [41 45 56]
  [ 4 34 63]
  [ 0 68 73]
  [95 82  4]]

 [[19 43 79]
  [24 40 31]
  [75 91 94]
  [24 53 65]
  [58 30  1]]]


In [50]:
ej_18.ndim

3

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [55]:
ej_19 = np.full(shape=(10,1), fill_value=False)
print(ej_19)
ej_19 = ej_19.reshape(2,5)
print(ej_19)

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]
[[False False False False False]
 [False False False False False]]


## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [56]:
x =np.random.randint(10, 20, size = (5,2,6))

In [60]:
print(f"x tiene {x.ndim} dimensiones")
print(f"x tiene {x.size} elementos")
print(f"cada dimensiones de x tiene {int(x.size/x.ndim)} elementos")

x tiene 3 dimensiones
x tiene 60 elementos
cada dimensiones de x tiene 20 elementos
